### ISSUE TITLE
Differentiation ILOs of RP1 and RP2

### ISSUE THREAD

**Issue by tijmz** [braincogsci/researchproject#20]
Thanks, @uop3612. Differentiation is on the right track. Some comments per learning objective, focusing on _Research Project 1_.

### Engage in the different phases of research in the field of brain and cognitive sciences (i.e. using and selecting relevant literature, performing experimental work, analyzing data).

Since we are specifying the phases, perhaps we can simplify and say the student can:
- Select and use relevant literature, perform experimental work and analyse experimental data

### Independently perform relevant scientific research method(s) and data analyses.**
Can this be merged with the former? Perhaps add independence to that one?

### Create a realistic planning for research, within the time limits that are imposed.
Not sure about this one. If the experimental design requirement isn't there, what does planning still mean? Perhaps it's better to talk about it in terms of project management. Then we can specify that in the rubrics in terms of organization, problem-solving, time management, etc. without emphasizing planning, which I think falls on the shoulders of the supervisor anyway -- and is a harder project management skill. So, for example, the student can:

- Organize work, manage time and work adaptively on a scientific project

(not sure this covers all relevant project management skills)

### Report about the project in a manner accordant to the norms and standards of the field
Seems right to me.

### Demonstrate academic presentation skills.
Seems right to me.

### Demonstrate a scientific attitude (independence, responsibility, perseverance, initiative, self-assessment, communication) within the work and in relation to the supervisor and colleagues.
This is good, as long as the rubrics reflect this and are specific about e.g. where student responsibility ends and the supervisor responsibility. As written, it is underspecifying what the level and scope of the listed qualities are.

### Reflect on and describe the limitations and implications of the research project.
Maybe we can explicitly add ethics to this ILO? E.g., the student can:

- Describe the scientific limitations and implications of the research project and reflect on its ethical aspects
Not a beauty of an ILO, but it puts discussion of the scientific qualities on equal footing with the ethical dimension.

**Comment by uop3612** [comment]
> **Engage in the different phases of research in the field of brain and cognitive sciences (i.e. using and selecting relevant literature, performing experimental work, analyzing data).**
Since we are specifying the phases, perhaps we can simplify and say the student can:
Select and use relevant literature, perform experimental work and analyse experimental data

I agree, but I would still add the fact that this should be in field of brain and cognitive sciences, so perhaps:
"Select and use relevant literature, perform experimental work and analyse experimental data within a research project in the field of brain and cognitive sciences"?

>**Independently perform relevant scientific research method(s) and data analyses.**
Can this be merged with the former? Perhaps add independence to that one?

Agreed, so this might become:
"Independently select and use relevant literature, perform experimental work and analyse experimental data within a research project in the field of brain and cognitive sciences"?

>**Create a realistic planning for research, within the time limits that are imposed.**
Not sure about this one. If the experimental design requirement isn't there, what does planning still mean? Perhaps it's better to talk about it in terms of project management. Then we can specify that in the rubrics in terms of organization, problem-solving, time management, etc. without emphasizing planning, which I think falls on the shoulders of the supervisor anyway -- and is a harder project management skill. So, for example, the student can:
Organize work, manage time and work adaptively on a scientific project
(not sure this covers all relevant project management skills)

I agree, perhaps project management could go into RP2, where we now expect students to also actively participate in project design?

>**Demonstrate a scientific attitude (independence, responsibility, perseverance, initiative, self-assessment, communication) within the work and in relation to the supervisor and colleagues.**
This is good, as long as the rubrics reflect this and are specific about e.g. where student responsibility ends and the supervisor responsibility. As written, it is underspecifying what the level and scope of the listed qualities are.

Do you think adding good rubrics is enough? Or do you have a suggestion on how to reformulate this?

>**Reflect on and describe the limitations and implications of the research project.**
Maybe we can explicitly add ethics to this ILO? E.g., the student can:
Describe the scientific limitations and implications of the research project and reflect on its ethical aspects
Not a beauty of an ILO, but it puts discussion of the scientific qualities on equal footing with the ethical dimension.

I agree, and we could explicitly ask students to write a paragraph about this, which would be important for the learning trajectories as well.
